#pragma once

#include "Structs.h"
#include <optional>

enum {LOG_CODE = 1, SIGN_CODE, ERROR_CODE, 
	NAME_EXIST_ERROR, NAME_DOES_NOT_EXIST_ERROR, ROOM_IS_ACTIVE, ROOM_IS_NOT_ACTIVE, 
	ROOM_DOES_NOT_EXIST, LOGOUT, GET_ROOMS, 
	GET_PLAYERS_IN_ROOM, JOIN_ROOM, CREATE_ROOM, 
	GET_HIGH_SCORE, GET_PERSONAL_STATS};
