#pragma once

#include "Structs.h"
#include <optional>


enum {LOG_CODE = 1, SIGN_CODE, ERROR_CODE, 
	NAME_EXIST_ERROR, NAME_DOES_NOT_EXIST_ERROR, ROOM_IS_ACTIVE, ROOM_IS_NOT_ACTIVE, 
	ROOM_DOES_NOT_EXIST, LOGOUT , FAIL_LOGOUT, GET_ROOMS, FAIL_GET_ROOMS, 
	GET_PLAYERS_IN_ROOM, FAIL_GET_PLAYERS_IN_ROOM,JOIN_ROOM, FAIL_JOIN_ROOM,CREATE_ROOM
	, FAIL_CREATE_ROOM, GET_HIGH_SCORE, FAIL_GET_HIGH_SCORE, GET_PERSONAL_STATS, FAIL_GET_PERSONAL_STATS, CLOSE_ROOM, FAIL_CLOSE_ROOM, LEAVE_ROOM, FAIL_LEAVE_ROOM, START_GAME, FAIL_START_GAME, GET_ROOM_STATE, FAIL_GET_ROOM_STATE
};
