#pragma once

#include "Structs.h"
#include <optional>

enum {LOG_CODE = 1, SIGN_CODE, ERROR_CODE, NAME_EXIST_ERROR, NAME_DOES_NOT_EXIST_ERROR, ROOM_IS_ACTIVE, ROOM_IS_NOT_ACTIVE, ROOM_DOES_NOT_EXIST};
